source "https://rubygems.org"

gem 'sass', '>=3.4.21', '< 3.5.0'
gem 'ffi', '1.9.10'
gem 'rb-inotify', '0.9.7'
gem 'rb-fsevent', '0.9.7'
gem 'compass-import-once', '1.0.5'
gem 'multi_json', '1.11.2'
gem 'compass-core', '1.0.3'
gem 'chunky_png', '>= 1.3.5', '< 1.3.6'
gem 'compass', '>=1.0.3', '< 1.1.0'
